artifacts_root: artifacts

data_ingestion:
  root_dir: data_ingestion
  source_URL: "https://github.com/rahul22106/End-to-End-Heart-Disease-Prediction-System/raw/refs/heads/main/Heart_Disease.zip"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/heart.csv
  STATUS_FILE: artifacts/data_validation/status.txt  
  
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/heart.csv
  transformed_data_dir: artifacts/data_transformation/transformed_data

model_trainer:
  root_dir: artifacts/model_trainer
  transformed_data_path: artifacts/data_transformation  # Path to transformed data
  trained_data_dir: artifacts/model_trainer/trained_model
  tested_data_dir: artifacts/model_trainer/test_results
  model_name: heart_disease_model.joblib