artifacts_root: artifacts

data_ingestion:
  root_dir: data_ingestion
  source_URL: "https://github.com/rahul22106/End-to-End-Heart-Disease-Prediction-System/raw/refs/heads/main/Heart_Disease.zip"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion